title               : Standard Auxiliary Private Limited
description         : >-                               # >- means to ignore newlines until "url:"
                      Enegy | Gases | Space Exploration | Research & Development

url                 : "https://vyshnav2255.github.io/Minimal-Portfolio-Website/"
repository          : Vyshnav2255/Minimal-Portfolio-Website 

email: info@stdaux.com
github_user: stdaux
instagram: stdauxhq
twitter: stdauxhq
dribbble: vyshnav_


exclude:
- README.md
- CONTRIBUTING.md
- LICENSE
- Gemfile
- Gemfile.lock
